export const db = [
  {
    id: 0,
    name: "Foto1",
    type: "Type1",
    season: "Season1",
    icon: "https://demo.retailtune.com/demo/1.jpg",
  },
  {
    id: 1,
    name: "Foto2",
    type: "Type2",
    season: "Season1",
    icon: "https://demo.retailtune.com/demo/2.jpg",
  },
  {
    id: 2,
    name: "Foto3",
    type: "Type3",
    season: "Season2",
    icon: "https://demo.retailtune.com/demo/3.jpg",
  },
  {
    id: 3,
    name: "Foto4",
    type: "Type1",
    season: "Season1",
    icon: "https://demo.retailtune.com/demo/4.jpg",
  },
  {
    id: 4,
    name: "Foto5",
    type: "Type2",
    season: "Season2",
    icon: "https://demo.retailtune.com/demo/5.jpg",
  },
  {
    id: 5,
    name: "Foto6",
    type: "Type3",
    season: "Season1",
    icon: "https://demo.retailtune.com/demo/6.jpg",
  },
  {
    id: 6,
    name: "Foto7",
    type: "Type1",
    season: "Season2",
    icon: "https://demo.retailtune.com/demo/7.jpg",
  },
  {
    id: 7,
    name: "Foto8",
    type: "Type2",
    season: "Season1",
    icon: "https://demo.retailtune.com/demo/8.jpg",
  },
  {
    id: 8,
    name: "Foto9",
    type: "Type3",
    season: "Season2",
    icon: "https://demo.retailtune.com/demo/9.jpg",
  },
];
